// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7EoqJxUaJYuSq1O-IiaqjrZ7ORu6Pxcc',
    appId: '1:902759665628:web:728f0c1ffb818d495d4919',
    messagingSenderId: '902759665628',
    projectId: 'foundationx-c3b2e',
    authDomain: 'foundationx-c3b2e.firebaseapp.com',
    storageBucket: 'foundationx-c3b2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCsfzDec3UrvHqiXajmkD5uCbyIpS9Zo4',
    appId: '1:902759665628:android:b8fa8429cac8d00b5d4919',
    messagingSenderId: '902759665628',
    projectId: 'foundationx-c3b2e',
    storageBucket: 'foundationx-c3b2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcOrFl9e5HedjP6yQalWA-W8pJpE5nso',
    appId: '1:902759665628:ios:8679c2f6417334145d4919',
    messagingSenderId: '902759665628',
    projectId: 'foundationx-c3b2e',
    storageBucket: 'foundationx-c3b2e.firebasestorage.app',
    iosBundleId: 'com.example.foundationx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcOrFl9e5HedjP6yQalWA-W8pJpE5nso',
    appId: '1:902759665628:ios:8679c2f6417334145d4919',
    messagingSenderId: '902759665628',
    projectId: 'foundationx-c3b2e',
    storageBucket: 'foundationx-c3b2e.firebasestorage.app',
    iosBundleId: 'com.example.foundationx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7EoqJxUaJYuSq1O-IiaqjrZ7ORu6Pxcc',
    appId: '1:902759665628:web:6ff3f6b1d81b4c815d4919',
    messagingSenderId: '902759665628',
    projectId: 'foundationx-c3b2e',
    authDomain: 'foundationx-c3b2e.firebaseapp.com',
    storageBucket: 'foundationx-c3b2e.firebasestorage.app',
  );
}